services:
    im0rtality_api.action.collection.count:
        class: Im0rtality\ApiBundle\Actions\Collection\CountAction
        tags:
            - { name: im0rtality_api.api.action.collection, resource: '*', action: count, method: GET }

    im0rtality_api.api.action.instance.read:
        class: Im0rtality\ApiBundle\Actions\Instance\ReadAction
        tags:
            - { name: im0rtality_api.api.action.instance, resource: '*', method: GET }

    im0rtality_api.api.action.instance.delete:
        class: Im0rtality\ApiBundle\Actions\Instance\DeleteAction
        tags:
            - { name: im0rtality_api.api.action.instance, resource: '*', method: DELETE }

    im0rtality_api.api.action.instance.update:
        class: Im0rtality\ApiBundle\Actions\Instance\UpdateAction
        tags:
            - { name: im0rtality_api.api.action.instance, resource: '*', method: PUT }

    im0rtality_api.api.action.collection.create:
        class: Im0rtality\ApiBundle\Actions\Collection\CreateAction
        tags:
            - { name: im0rtality_api.api.action.collection, resource: '*', method: POST }

    im0rtality_api.api.action.collection.index:
        class: Im0rtality\ApiBundle\Actions\Collection\IndexAction
        tags:
            - { name: im0rtality_api.api.action.collection, resource: '*', method: GET }
