im0rtality_api.resource.instance.action:
    path:     /{resource}/{identifier}/{actionName}
    defaults:
        _controller: Im0rtalityApiBundle:Api:custom
        _format: json
    requirements:
        identifier: \d+

im0rtality_api.resource.instance.action.empty_action:
    path:     /{resource}/{identifier}
    defaults:
        _controller: Im0rtalityApiBundle:Api:custom
        actionName: ~
        _format: json
    requirements:
        identifier: \d+

im0rtality_api.resource.collection.action:
    path:     /{resource}/{actionName}
    defaults:
        _controller: Im0rtalityApiBundle:Api:custom
        _format: json
    methods: [GET, POST, PUT, DELETE, HEAD]

im0rtality_api.resource.collection.action.empty_action:
    path:     /{resource}
    defaults:
        _controller: Im0rtalityApiBundle:Api:custom
        actionName: ~
        _format: json
