parameters:

services:
    im0rtality_api.data_source.doctrine.orm.class_factory:
        class: Im0rtality\ApiBundle\DataSource\ClassFactory

    im0rtality_api.data_source.orm:
        class: Im0rtality\ApiBundle\DataSource\DoctrineOrmSource
        calls:
            - [setClassFactory, [@im0rtality_api.data_source.doctrine.orm.class_factory]]
            - [setRegistry, [@doctrine]]

    im0rtality_api.data_source.factory:
        class: Im0rtality\ApiBundle\DataSource\Factory\DataSourceFactory

    im0rtality_api.action.manager:
        class: Im0rtality\ApiBundle\Actions\ActionManager

    im0rtality_api.api.resource_resolver:
        class: Im0rtality\ApiBundle\Helper\ResourceResolver
        calls:
            - [setResourceMapping, [%im0rtality_api.config.mapping%]]

    im0rtality_api.api.security.permissions:
        class: Im0rtality\ApiBundle\Security\PermissionManager
        calls:
            - [setAcl, [%api_bundle_api.config.security.acl%]]

    im0rtality_api.api.security.request_validator:
        class: Im0rtality\ApiBundle\Helper\RequestValidator
        calls:
            - [setPermissions, [@im0rtality_api.api.security.permissions]]

    im0rtality_api.api.security.response_filter:
        class: Im0rtality\ApiBundle\Helper\ResponseFilter
        calls:
            - [setPermissions, [@im0rtality_api.api.security.permissions]]
            - [setSerializer, [@jms_serializer]]

    im0rtality_api.api.security.ownership_resolver:
        class: Im0rtality\ApiBundle\Helper\OwnershipResolver
        calls:
            - [setOwnerships, [%im0rtality_api.config.ownership%]]
