language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: hhvm
before_install:
    # to avoid Github API rate limiting (scope - repo:status)
    - composer config -g github-oauth.github.com 4a5d830c53e21564d03c452c7624cad41a1d49bc
    - printenv TRAVIS_TAG
    - false

install:
    - composer install -n --prefer-dist
    - cd test; composer install -n --prefer-dist

script:
    - bin/phpspec run -v -fpretty
    - cd test; bin/behat -v -fpretty
