language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

install:
    - composer install -n --prefer-source

script:
    - bin/phpspec run -v -fpretty
